SupermercadoVirtual/Models/Elemento.cs
namespace SupermercadoVirtual.Models
{
    public class Elemento
    {
        public Producto producto { get; set; }
        public int cantidad { get; set; }
    }
}

SupermercadoVirtual/Models/ErrorViewModel.cs
using System;

namespace SupermercadoVirtual.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SupermercadoVirtual/Models/Producto.cs
namespace SupermercadoVirtual.Models
{
    public class Producto
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public double precio { get; set; }
        public string imagen { get; set; }
    }
}

SupermercadoVirtual/Models/ProductoModel.cs
using System.Collections.Generic;
using System.Linq;

namespace SupermercadoVirtual.Models
{
    public class ProductoModel
    {
        //Clase de apoyo para poder contar, rápidamente, con una lista de productos y con métodos de consulta.
        private List<Producto> productos;
        public ProductoModel()
        {
            productos = new List<Producto>()
            {
                new Producto
                {
                    id = 1,
                    nombre = "Atún VanCamps",
                    precio = 12,
                    imagen = "atun.jpg"
                },
                new Producto
                {
                    id = 2,
                    nombre = "Queso menonita",
                    precio = 45,
                    imagen = "queso.jpg"
                }
            };
        }
        public List<Producto> getTodo()
        {
            return productos;
        }
        public Producto getById(int id)
        {
            return productos.Single(prod => prod.id == id);
        }
    }
}

SupermercadoVirtual/Controllers/CarritoController.cs
using Microsoft.AspNetCore.Mvc;
using SupermercadoVirtual.Helper;
using SupermercadoVirtual.Models;
using System.Collections.Generic;
using System.Linq;

namespace SupermercadoVirtual.Controllers
{
    public class CarritoController : Controller
    {
        public IActionResult Index()
        {
            List<Elemento> carrito = SesionHelper.GetJsonToObjeto<List<Elemento>>(HttpContext.Session, "carrito");
            if(carrito != null && carrito.Count > 0)
            {
                //Le pasamos la lista de elementos
                ViewBag.carrito = carrito;
                //Le pasamos el total que lo obtenemos desde controlador (también podría ser obtenido en vista)
                ViewBag.total = carrito.Sum(elem => elem.producto.precio * elem.cantidad);
            }
            else
            {
                ViewBag.carrito = new List<Elemento>();
                ViewBag.total = 0;
            }
            
            return View();
        }

        [Route("comprar/{id}")]
        public IActionResult Comprar(int id)
        {
            ProductoModel pm = new ProductoModel();//Aca estan los métodos de consulta sobre el conjunto de productos

            if (SesionHelper.GetJsonToObjeto<List<Elemento>>(HttpContext.Session, "carrito") == null) {
                List<Elemento> carrito = new List<Elemento>();
                carrito.Add(new Elemento { producto = pm.getById(id), cantidad = 1 });
                SesionHelper.SetObjetoToJson(HttpContext.Session, "carrito", carrito);
            }else
            {
                List<Elemento> carrito = SesionHelper.GetJsonToObjeto<List<Elemento>>(HttpContext.Session, "carrito");
                var indice = getIndice(id);
                if (indice != -1)//caso1: que quiera añadir un producto que ya está en el carrito
                    carrito[indice].cantidad++;
                else//caso2: que quiera añadir un producto que no está en el carrito
                    carrito.Add(new Elemento { producto = pm.getById(id), cantidad = 1 });

                SesionHelper.SetObjetoToJson(HttpContext.Session, "carrito", carrito);
            }
            return RedirectToAction("Index");
        }
        private int getIndice(int id)//Exactamente el código mostrado en clases
        {
            List<Elemento> carrito = SesionHelper.GetJsonToObjeto<List<Elemento>>(HttpContext.Session, "carrito");
            for (int i = 0; i < carrito.Count; i++)
            {
                if (carrito[i].producto.id == id)
                    return i;
            }
            return -1;
        }
        [Route("eliminar/{id}")]
        public IActionResult Eliminar(int id)
        {
            List<Elemento> carrito = SesionHelper.GetJsonToObjeto<List<Elemento>>(HttpContext.Session, "carrito");
            int indice = getIndice(id);
            if(indice != -1)//existe
            {
                carrito[indice].cantidad--;
                if (carrito[indice].cantidad <= 0)
                    carrito.RemoveAt(indice);
                SesionHelper.SetObjetoToJson(HttpContext.Session, "carrito", carrito);
            }
            return RedirectToAction("Index");
        }

        public IActionResult Vaciar()
        {
            List<Elemento> carrito = SesionHelper.GetJsonToObjeto<List<Elemento>>(HttpContext.Session, "carrito");
            ViewBag.total = carrito.Sum(elem => elem.producto.precio * elem.cantidad);
            carrito = new List<Elemento>();
            SesionHelper.SetObjetoToJson(HttpContext.Session, "carrito", carrito);
            return View("Listo");
        }
    }
}

SupermercadoVirtual/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SupermercadoVirtual.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace SupermercadoVirtual.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SupermercadoVirtual/Controllers/PrincipalController.cs
using Microsoft.AspNetCore.Mvc;
using SupermercadoVirtual.Models;

namespace SupermercadoVirtual.Controllers
{
    [Route("principal")]
    public class PrincipalController : Controller
    {
        [Route("")]
        [Route("~/")]
        [Route("index")]
        public IActionResult Index()
        {
            ProductoModel pm = new ProductoModel();
            ViewBag.productos = pm.getTodo();//Lo resuelvo pasandole la lista por viewBag, pero sin mezclar lógica de negocios en controlador.
            return View();
        }
    }
}

SupermercadoVirtual/Views/Carrito/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h3>Tu carrito</h3>

<table class="table">
    <thead>
        <tr>
            <th sscope="col">Nombre</th>
            <th sscope="col">Imagen</th>
            <th sscope="col">Precio</th>
            <th sscope="col">Cantidad</th>
            <th sscope="col">Acción</th>
            <th sscope="col">Subtotal</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var elem in ViewBag.carrito)
        {
            <tr>
                <td>@elem.producto.nombre</td>
                <td><img src="~/imagenes/@elem.producto.imagen" width="100"/></td>
                <td>@elem.producto.precio</td>
                <td>@elem.cantidad</td>
                <td><a asp-controller="Carrito" asp-action="Eliminar" asp-route-id="@elem.producto.id">Eliminar uno</a></td>
                <td>@(elem.producto.precio * elem.cantidad)</td>
            </tr>
        }
        <tr>
            <td colspan="5" align="right">Total:</td>
            <td>@ViewBag.total</td>
        </tr>
    </tbody>
</table>
<a asp-controller="principal" asp-action="index">Volver atrás</a>
<a asp-controller="Carrito" asp-action="Vaciar">Finalizar compra</a>

SupermercadoVirtual/Views/Carrito/Listo.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h3>¡Gracias por su compra!</h3>
<p>Se le descontó Bs.@ViewBag.total</p>
<a asp-controller="principal" asp-action="index">Regresar a la página principal</a>

SupermercadoVirtual/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SupermercadoVirtual/Views/Principal/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h3>Productos disponnibles</h3>
<a asp-controller="Carrito" asp-action="Index">Ver carrito</a>
<table class="table">
    <thead>
        <tr>
            <th sscope="col">ID</th>
            <th sscope="col">Nombre</th>
            <th sscope="col">Imagen</th>
            <th sscope="col">Precio</th>
            <th sscope="col">Acción</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var prod in ViewBag.productos)
        {
            <tr>
                <td scope="row">@prod.id</td>
                <td>@prod.nombre</td>
                <td><img src="~/imagenes/@prod.imagen" width="100"/></td>
                <td>@prod.precio</td>
                <td><a asp-controller="Carrito" asp-action="Comprar" asp-route-id="@prod.id">Comprar ahora</a></td>
            </tr>
        }
    </tbody>
</table>

SupermercadoVirtual/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SupermercadoVirtual</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SupermercadoVirtual</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - SupermercadoVirtual - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>